spring:
  application:
    name: demo
  datasource:
    url: # TODO URL
    username: # TODO USERNAME
    password: # TODO PASSWORD
  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.generate_statistics: true
logging:
  level:
    root: info